### ISSUE TITLE
Why so constrained work area?

### ISSUE THREAD

**Issue by danielo515** [TargetProcess/mongo-mapreduce-debug-online#2]
Hello,

Thank you very much for your tool. It is saving my life.

One thing that I don't understand is why have you limited the work area to just 640px. I have to hack the css to have a wider work area, which is essential to work comfortably.

Thanks and regards

**Comment by vladminsky** [comment]
@danielo515 

Daniel, I'm happy to hear you find the tool useful!
I just set width to 80% of the body. Hope it is enough for comfortable work.
If you have better ideas on the topic - share your expectations or send pull request.

Regards,
Vladimir

**Comment by danielo515** [comment]
Hello @vladminsky,

Thank you very much for such a fast fix. 80% is a perfect size for working comfortably. 

Indeed I will give you my feedback on this topic and any other I find :smile:
